/**********************************************************************
 *
 * Copyright (c) 2023 Olaf Willuhn, Mathias Behrle
 * All rights reserved.
 * 
 * This software is copyrighted work licensed under the terms of the
 * Jameica License.  Please consult the file "LICENSE" for details. 
 *
 **********************************************************************/

package de.willuhn.jameica.hbci.paypal.synchronize;

import java.util.HashMap;

public class PaypalTcodes {
  static HashMap<String, String> credit_tcodes = new HashMap<>();
  static HashMap<String, String> debit_tcodes = new HashMap<>();

  // structure:
  // "T-Code", "Description|SubCategory|Additional information"
  // https://developer.paypal.com/docs/reports/reference/tcodes/
  static {
    credit_tcodes.put("T1300", "General Authorizations|Authorizations|");
    credit_tcodes.put("T1302", "Void of Authorizations|Authorizations|");
    credit_tcodes.put("T1301", "ReAuthorization|ReAuthorization|");
    credit_tcodes.put("T1201", "Chargeback|Chargeback Activity|");
    credit_tcodes.put("T1202", "Chargeback Reversal|Chargeback Activity|Reversals (Chargebacks won, where the merchant receives a reimbursement for the Chargeback amount).");
    credit_tcodes.put("T1208", "PACMAN Buyer cancellation|Chargeback Activity|Adjustment to PayPal Account for Reversal of chargeback reversal based on cancellation of a chargeback in PayPal.");
    credit_tcodes.put("T1207", "PACMAN Represenment Rejected|Chargeback Activity|Adjustment to PayPal Account for Reversal of payment based on rejection of the representment for a chargeback in PayPal.");
    credit_tcodes.put("T1106", "Payment Reversal|Chargeback Activity|Initiated by PayPal.");
    credit_tcodes.put("T1205", "Reimbursement of Chargeback|Chargeback Activity|");
    credit_tcodes.put("T1111", "Cancellation of Hold for Dispute Resolution|Chargeback Releases|Cancellation of temporary hold to cover possible chargeback.");
    credit_tcodes.put("T1110", "Hold on Balance for Dispute Investigation|Chargeback Releases|Hold to cover possible chargeback.");
    credit_tcodes.put("T1106", "Payment Reversal|Chargeback Reversals|Initiated by PayPal.");
    credit_tcodes.put("T2000", "General intraaccount transfer|Account Transfer|");
    credit_tcodes.put("T2003", "Transfer To External GL Entity|Account Transfer|");
    credit_tcodes.put("T2004", "Receivables financing|Account Transfer|Applicable only in Brazil.");
    credit_tcodes.put("T1203", "Charge-off Adjustment|Adjustments|");
    credit_tcodes.put("T1200", "General Account Adjustment|Adjustments|");
    credit_tcodes.put("T1204", "Incentive Adjustment|Adjustments|");
    credit_tcodes.put("T0803", "Balance Manager Account Bonus|Balance Manager Account Bonus|");
    credit_tcodes.put("T1000", "BillPay transaction|BillPay transaction|");
    credit_tcodes.put("T1601", "BML Credit - Transfer from BML|BML Credit -Transfer from BML|");
    credit_tcodes.put("T1801", "BML Withdrawal - Transfer to BML|BML WithdrawalTransfer to BML|");
    credit_tcodes.put("T1603", "Buyer Credit Payment Withdrawal - Transfer To BML|BML WithdrawalTransfer to BML|");
    credit_tcodes.put("T0806", "Bonus for First ACH Use|Bonus for Bank Funding Program|");
    credit_tcodes.put("T1900", "General Account Correction|Correction Adjustment|");
    credit_tcodes.put("T0903", "Coupon Redemption|Coupon applied|");
    credit_tcodes.put("T0808", "Credit Card Cash Back Bonus|Credit Card Cash Back Bonus|The monthly cash back accrued based on PayPal Extras Card signatures transactions for cash back program enrollees.");
    credit_tcodes.put("T0701", "Credit Card Deposit for Negative PayPal Account Balance|Credit Card Deposit|");
    credit_tcodes.put("T0807", "CC Security Charge Refund|Credit Card Security Credit|");
    credit_tcodes.put("T0801", "Debit Card Cash Back Bonus|Debit Card Cash Back Bonus|Requires a PayPal debit card associated with the PayPal account. The monthly cash back accrued based on Merchant Debit Card signatures transactions for cash back program enrollees.");
    credit_tcodes.put("T0503", "Hidden Virtual PayPal Debit Card Transaction|Debit card purchase|");
    credit_tcodes.put("T1102", "Reversal of Debit Card Transaction|Debit Card Reversal|Reversal of a debit card payment. Requires a PayPal debit card.");
    credit_tcodes.put("T0303", "Electronic Funds Transfer Funding|Electronic Funds Transfer|");
    credit_tcodes.put("T0800", "General Bonus|General Bonus|");
    credit_tcodes.put("T0700", "General Credit Card Deposit|General Credit Card Deposit|Purchase with a credit card.");
    credit_tcodes.put("T0600", "General Credit Card Withdrawal|General Credit Card Withdrawal|Reversal of purchase with a credit card. Seen only in PayPal account of the credit card owner.");
    credit_tcodes.put("T1400", "General Dividend|General Dividend|");
    credit_tcodes.put("T0900", "General Incentive/Certificate Redemption|General Incentive/Certificate Redemption|");
    credit_tcodes.put("T1100", "General Reversal|General Reversal|");
    credit_tcodes.put("T1700", "General withdrawal to not bank entity|General Withdrawal to Non-Bank Institution|");
    credit_tcodes.put("T3000", "General GI/Open wallet Transaction|Generic instrument(PLCC)|");
    credit_tcodes.put("T0901", "Gift Certificate Redemption|Gift Certificate applied|");
    credit_tcodes.put("T1116", "Instant Payment Review (IPR)reversal|Instant Payment Review|");
    credit_tcodes.put("T0802", "Merchant Referral Account Bonus|Merchant Referral Account Bonus|Must have created a Merchant Referral Bonus link.");
    credit_tcodes.put("T0905", "MSB Redemption|MSB Redemption|");
    credit_tcodes.put("T0500", "General PayPal Debit Card Transaction|Other debit card activity|Requires a PayPal debit card associated with the PayPal account.");
    credit_tcodes.put("T0505", "PayPal Debit Authorization|Other debit card activity|");
    credit_tcodes.put("T0504", "PayPal Debit Card Cash Advance|Other debit card activity|Initiated by PayPal.");
    credit_tcodes.put("T0501", "Virtual PayPal Debit Card Transaction|Other debit card activity|");
    credit_tcodes.put("T1115", "Mass Pay Refund|Payment Refund|");
    credit_tcodes.put("T1107", "Payment Refund|Payment Refund|");
    credit_tcodes.put("T1119", "Generic Instrument/Open wallet Reversals (Buyer side)|Payment Reversals|");
    credit_tcodes.put("T1114", "Mass Pay Reversal|Payment Reversals|");
    credit_tcodes.put("T0804", "PayPal Buyer Warranty Bonus|PayPal Buyer Warranty Bonus|");
    credit_tcodes.put("T0502", "PayPal Debit Card Withdrawal to ATM|PayPal Debit Card Withdrawal to ATM|");
    credit_tcodes.put("T0805", "PayPal Protection Bonus, Payout for PayPal Buyer Protection, Payout for Full Protection with PayPal Buyer Credit|PayPal Protection Credit|");
    credit_tcodes.put("T0902", "Points Incentive Redemption|Points Incentive applied|");
    credit_tcodes.put("T1104", "Reversal of ACH Deposit|Reversal of ACH Deposit|");
    credit_tcodes.put("T1101", "Reversal of ACH Withdrawal Transaction|Reversal of ACH Withdrawal Transaction|Reversal of a withdrawal from PayPal balance to a bank account.");
    credit_tcodes.put("T1103", "Reversal of Points Usage|Reversal of Points Usage|");
    credit_tcodes.put("T1118", "Generic Instrument/Open wallet Reversals (Seller side)|Reversals|");
    credit_tcodes.put("T0904", "Reward Voucher Redemption|Reward Voucher applied|");
    credit_tcodes.put("T2001", "Consolidation Transfer|Settlement consolidation|");
    credit_tcodes.put("T0302", "ACH funding for Funds Recovery from Account balance|Transfer Deposit|");
    credit_tcodes.put("T0300", "Bank Deposit to PP Account|Transfer Deposit|");
    credit_tcodes.put("T0301", "PayPal Balance Manager Funding of PayPal Account|Transfer Deposit|PayPal-system generated.");
    credit_tcodes.put("T0401", "Auto-sweep|Transfer Withdrawal|");
    credit_tcodes.put("T0400", "General Withdrawal - Bank Account|Transfer Withdrawal|Settlement Withdrawal.");
    credit_tcodes.put("T1701", "World Link withdrawal|World Link Withdrawal|");
    credit_tcodes.put("T0106", "Chargeback Fee|Chargeback fee|Fees charged to a merchant for a credit card chargeback received.");
    credit_tcodes.put("T0100", "General NonPayment Related Fee|Fee|");
    credit_tcodes.put("T1109", "Fee Refund|Fee Credits|Fees refunded when refunds are issued.");
    credit_tcodes.put("T1108", "Fee Reversal|Fee Credits|");
    credit_tcodes.put("T0104", "Fee for Mass Pay request|Payment Fee|");
    credit_tcodes.put("T0113", "Partner Fee|Payment Fee|");
    credit_tcodes.put("T0107", "Payment Fee|Payment Fee|Fees charged for payments received, plus fees charged for sending Mass Payments.");
    credit_tcodes.put("T0101", "Web Site Payment Pro Account Monthly Fee|Product Fee|");
    credit_tcodes.put("T0102", "Fee for Foreign ACH withdrawal|Product Fee|");
    credit_tcodes.put("T0103", "Fee for World Link Check withdrawal|Product Fee|");
    credit_tcodes.put("T1109", "Fee Refund|Service Fee|Fees refunded when refunds are issued.");
    credit_tcodes.put("T0112", "Gift Certificate Expiration Fee|Service Fee|");
    credit_tcodes.put("T0110", "International CC withdrawal|Service Fee|");
    credit_tcodes.put("T0111", "Warranty Fee for warranty purchase|Service Fee|");
    credit_tcodes.put("T0108", "ATM withdrawal|Service Fee|");
    credit_tcodes.put("T0109", "Auto-sweep from account|Service Fee|");
    credit_tcodes.put("T0105", "Check withdrawal|Service Fee|");
    credit_tcodes.put("T0114", "Dispute Fee|Service Fee|");
    credit_tcodes.put("T0115", "Custody Fee|Service Fee|Service fee charged as a custody fee if user holds balance beyond allowed threshold during that period.");
    credit_tcodes.put("T0116", "Bank Return Fee|Service Fee|");
    credit_tcodes.put("T9900", "Other|Other|");
    credit_tcodes.put("T9800", "Display only transaction row|Other - Non- balance Impacting|");
    credit_tcodes.put("T9701", "Funds Payable|Funds payable|Funds provided by PayPal that need to be paid back.");
    credit_tcodes.put("T9702", "Funds Receivable|Funds payable|Funds provided by PayPal that are being paid back.");
    credit_tcodes.put("T9700", "Payables and Receivables|Payables and Receivables|");
    credit_tcodes.put("T0010", "3rd Party Auction Payment|3rd Party Auction Payment|");
    credit_tcodes.put("T0017", "Chained Payment/Refund|Chained Payment/Refund|Store to store transfer.");
    credit_tcodes.put("T0005", "Direct Credit Card Payment|Direct Credit Card Payment|");
    credit_tcodes.put("T0013", "Donation Payment|Donation Payment|");
    credit_tcodes.put("T0004", "eBay Auction Payment|eBay Auction Payment|");
    credit_tcodes.put("T0006", "Express Checkout Payment|Express Checkout Payment|");
    credit_tcodes.put("T1602", "Buyer Credit Payment|General Buyer Credit Payment|");
    credit_tcodes.put("T1800", "General Buyer Credit Payment|General Buyer Credit Payment|Must have signed up for Buyer Credit.");
    credit_tcodes.put("T0000", "General Payment|General payment|");
    credit_tcodes.put("T0019", "Generic Instrument funded Payment|Generic Instrument funded Payment|");
    credit_tcodes.put("T0009", "Gift Certificate Payment (Purchase)|Gift Certificate Purchase|");
    credit_tcodes.put("T1112", "Cancelled Transfer|MAM Reversal|");
    credit_tcodes.put("T0001", "Mass Pay Payment|Mass Pay payment|");
    credit_tcodes.put("T0011", "Mobile Payment|Mobile Payment|Payment made via a mobile phone.");
    credit_tcodes.put("T0003", "PreApproved Payment Bill User Payment|Payment Bill User Payment|");
    credit_tcodes.put("T2201", "Digital goods transaction|Payments received|Transfer from a credit card funded restricted balance.");
    credit_tcodes.put("T1113", "Non Reference Credit Payment|Payments received|");
    credit_tcodes.put("T1600", "PayPal Buyer Credit Payment Funding|PayPal Buyer Credit Payment Funding|Must have signed up for Buyer Credit.");
    credit_tcodes.put("T0018", "PayPal Here Payment|PayPal Here Payment|");
    credit_tcodes.put("T0008", "Postage Payment|Postage Payment|Payment to postage carrier.");
    credit_tcodes.put("T0014", "Rebate Payment/Cash Back|Rebate Payment/Cash Back|");
    credit_tcodes.put("T1117", "Rebate/Cashback reversal|Rebate/Cash back reversal|");
    credit_tcodes.put("T0002", "Subscription Payment|Subscription Payment|");
    credit_tcodes.put("T0020", "Tax collected by Partner|Tax collected by Partner|Refund of tax amount collected by Partners or Marketplaces in the event of a refund, reversal, or chargeback of a sale transaction.");
    credit_tcodes.put("T0015", "Third Party Payout|Third Party Payout|");
    credit_tcodes.put("T0016", "Third Party Recoupment|Third Party Recoupment|");
    credit_tcodes.put("T0012", "Virtual Terminal Payment|Virtual Terminal Payment|");
    credit_tcodes.put("T0007", "Website Payment|Website Payment|");
    credit_tcodes.put("T0021", "Cryptocurrency|Cryptocurrency|");
    credit_tcodes.put("T0022", "PayPal Seller Profiles|PayPal Seller Profiles|");
    credit_tcodes.put("T1502", "Account Hold for ACH deposit|Account Release|");
    credit_tcodes.put("T2113", "Blocked Payments|Account Release|");
    credit_tcodes.put("T2111", "External Hold|Account Release|");
    credit_tcodes.put("T1500", "General Account Hold|Account Release|");
    credit_tcodes.put("T2101", "General Hold|Account Release|");
    credit_tcodes.put("T2102", "General Hold Release|Account Release|");
    credit_tcodes.put("T1503", "Hold on Available Balance|Account Release|");
    credit_tcodes.put("T2109", "Gift Certificate Purchase|Gift Card redemption|When a gift certificate is purchased by your buyer, then that amount is placed on hold.");
    credit_tcodes.put("T2110", "Gift Certificate Redemption|Gift Certificate Redemption|A gift certificate, when redeemed, is available for withdrawal.");
    credit_tcodes.put("T1501", "Account Hold for Open Authorization|Open PayPal Authorizations|");
    credit_tcodes.put("T2107", "Payment Hold|Payment review release|Payment holds are funds that belong to you that we set aside, such as security deposit. This amount is part of your total balance and will not be available for withdrawal.");
    credit_tcodes.put("T2105", "Payment Review Hold|Payment review release|A payment review hold is used to protect you against unauthorized fraud loss and for seller protection. While a transaction is on payment review hold, we recommend that you do not ship the item. We are reviewing this transaction for up to 24 hours.");
    credit_tcodes.put("T1105", "Reversal of General Account Hold|Release|");
    credit_tcodes.put("T2108", "Payment Release|Release on payment review release|A payment hold, when released, is now available for withdrawal.");
    credit_tcodes.put("T2106", "Payment Review Release|Release on payment review release|A payment review hold, when released, is now available for withdrawal.");
    credit_tcodes.put("T2112", "External Release|Release on risk release|");
    credit_tcodes.put("T2115", "Release on tax hold|Tax release|A tax hold, when released, is now available for withdrawal.");
    credit_tcodes.put("T2103", "Reserve Hold|Reserve Release|PayPal is holding x% of funds for y days as a condition for processing for you. This amount is part of your total balance and will not be available for withdrawal.");
    credit_tcodes.put("T2104", "Reserve Release|Reserve Release|A reserve, when released, is now available for withdrawal.");
    credit_tcodes.put("T0202", "Conversion to Cover Negative Balance|Currency Conversion|PayPal-system generated.");
    credit_tcodes.put("T0200", "General Currency Conversion|Currency Conversion|Transfer of funds from one currency balance to a different currency balance.");
    credit_tcodes.put("T0201", "User Initiated Currency Conversion|Currency Conversion|");
    credit_tcodes.put("T0117", "Campaign Fee|Campaign Fee|");
    
    debit_tcodes.put("T0117", "Campaign Fee|Campaign Fee|");
    debit_tcodes.put("T1300", "General Authorizations|Authorizations|");
    debit_tcodes.put("T1302", "Void of Authorizations|Authorizations|");
    debit_tcodes.put("T1301", "ReAuthorization|ReAuthorization|");
    debit_tcodes.put("T1201", "Chargeback|Chargeback Activity|");
    debit_tcodes.put("T1202", "Chargeback Reversal|Chargeback Activity|Reversals (Chargebacks won, where the merchant receives a reimbursement for the Chargeback amount).");
    debit_tcodes.put("T1208", "PACMAN Buyer cancellation|Chargeback Activity|Adjustment to PayPal Account for Reversal of chargeback reversal based on cancellation of a chargeback in PayPal.");
    debit_tcodes.put("T1207", "PACMAN Represenment Rejected|Chargeback Activity|Adjustment to PayPal Account for Reversal of payment based on rejection of the representment for a chargeback in PayPal.");
    debit_tcodes.put("T1106", "Payment Reversal|Chargeback Activity|Initiated by PayPal.");
    debit_tcodes.put("T1205", "Reimbursement of Chargeback|Chargeback Activity|");
    debit_tcodes.put("T1201", "Chargeback|Chargeback Adjustments|");
    debit_tcodes.put("T1202", "Chargeback Reversal|Chargeback Adjustments|");
    debit_tcodes.put("T1208", "PACMAN Buyer cancellation|Chargeback Adjustments|Adjustment to PayPal Account for Reversal of chargeback reversal based on cancellation of a chargeback in the PayPal system.");
    debit_tcodes.put("T1207", "PACMAN Represenment Rejected|Chargeback Adjustments|Adjustment to PayPal Account for Reversal of payment based on rejection of the representment for a chargeback in PayPal.");
    debit_tcodes.put("T1205", "Reimbursement of Chargeback|Chargeback Adjustments|");
    debit_tcodes.put("T1111", "Cancellation of Hold for Dispute Resolution|Chargeback Hold|Cancellation of temporary hold to cover possible chargeback.");
    debit_tcodes.put("T1110", "Hold on Balance for Dispute Investigation|Chargeback Hold|Hold to cover possible chargeback.");
    debit_tcodes.put("T2002", "Withdraw funds to Partner Account|Account Transfer|");
    debit_tcodes.put("T0106", "Chargeback Fee|Chargeback fee|Fees charged to a merchant for a credit card chargeback received.");
    debit_tcodes.put("T0100", "General NonPayment Related Fee|Fee|");
    debit_tcodes.put("T1109", "Fee Refund|Fee Credits|Fees refunded when refunds are issued.");
    debit_tcodes.put("T1108", "Fee Reversal|Fee Credits|");
    debit_tcodes.put("T0104", "Fee for Mass Pay request|Payment Fee|");
    debit_tcodes.put("T0113", "Partner Fee|Payment Fee|");
    debit_tcodes.put("T0107", "Payment Fee|Payment Fee|Fees charged for payments received, plus fees charged for sending Mass Payments.");
    debit_tcodes.put("T0101", "Web Site Payment Pro Account Monthly Fee|Product Fee|");
    debit_tcodes.put("T0102", "Fee for Foreign ACH withdrawal|Product Fee|");
    debit_tcodes.put("T0103", "Fee for World Link Check withdrawal|Product Fee|");
    debit_tcodes.put("T1109", "Fee Refund|Service Fee|Fees refunded when refunds are issued.");
    debit_tcodes.put("T0112", "Gift Certificate Expiration Fee|Service Fee|");
    debit_tcodes.put("T0110", "International CC withdrawal|Service Fee|");
    debit_tcodes.put("T0111", "Warranty Fee for warranty purchase|Service Fee|");
    debit_tcodes.put("T0108", "ATM withdrawal|Service Fee|");
    debit_tcodes.put("T0109", "Auto-sweep from account|Service Fee|");
    debit_tcodes.put("T0105", "Check withdrawal|Service Fee|");
    debit_tcodes.put("T0114", "Dispute Fee|Service Fee|");
    debit_tcodes.put("T0115", "Custody Fee|Service Fee|Service fee charged as a custody fee if user holds balance beyond allowed threshold during that period.");
    debit_tcodes.put("T0116", "Bank Return Fee|Service Fee|");
    debit_tcodes.put("T9900", "Other|Other|");
    debit_tcodes.put("T9800", "Display only transaction row|Other - Non- balance Impacting|");
    debit_tcodes.put("T0010", "3rd Party Auction Payment|3rd Party Auction Payment|");
    debit_tcodes.put("T0017", "Chained Payment/Refund|Chained Payment/Refund|Store to store transfer.");
    debit_tcodes.put("T0005", "Direct Credit Card Payment|Direct Credit Card Payment|");
    debit_tcodes.put("T0013", "Donation Payment|Donation Payment|");
    debit_tcodes.put("T0004", "eBay Auction Payment|eBay Auction Payment|");
    debit_tcodes.put("T0006", "Express Checkout Payment|Express Checkout Payment|");
    debit_tcodes.put("T1603", "Buyer Credit Payment Withdrawal - Transfer To BML|General Buyer Credit Payment|");
    debit_tcodes.put("T1800", "General Buyer Credit Payment|General Buyer Credit Payment|Must have signed up for Buyer Credit");
    debit_tcodes.put("T0000", "General Payment|General payment|");
    debit_tcodes.put("T0019", "Generic Instrument funded Payment|Generic Instrument funded Payment|");
    debit_tcodes.put("T0009", "Gift Certificate Payment(Purchase)|Gift Certificate Purchase|");
    debit_tcodes.put("T1112", "Cancelled Transfer|MAM Reversal|");
    debit_tcodes.put("T0001", "Mass Pay Payment|Mass Pay payment|");
    debit_tcodes.put("T0011", "Mobile Payment|Mobile Payment|Payment made via a mobile phone.");
    debit_tcodes.put("T0003", "PreApproved Payment Bill User Payment|Payment Bill User Payment|");
    debit_tcodes.put("T2201", "Digital goods transaction|Payment Sent|Transfer from a credit card funded restricted balance.");
    debit_tcodes.put("T1113", "Non Reference Credit Payment|Payment Sent|");
    debit_tcodes.put("T1600", "PayPal Buyer Credit Payment Funding|PayPal Buyer Credit Payment Funding|Must have signed up for Buyer Credit.");
    debit_tcodes.put("T0018", "PayPal Here Payment|PayPal Here Payment|");
    debit_tcodes.put("T0008", "Postage Payment|Postage Payment|");
    debit_tcodes.put("T0014", "Rebate Payment/Cash Back|Rebate Payment/Cash Back|");
    debit_tcodes.put("T1117", "Rebate/Cashback reversal|Rebate/Cashback reversal|");
    debit_tcodes.put("T0002", "Subscription Payment|Subscription Payment|");
    debit_tcodes.put("T0020", "Tax collected by Partner|Tax collected by Partner|Tax collected by Partners or Marketplaces on your sale transactions.");
    debit_tcodes.put("T0015", "Third Party Payout|Third Party Payout|");
    debit_tcodes.put("T0016", "Third Party Recoupment|Third Party Recoupment|");
    debit_tcodes.put("T0012", "Virtual Terminal Payment|Virtual Terminal Payment|");
    debit_tcodes.put("T0007", "Website Payment|Website Payment|");
    debit_tcodes.put("T0021", "Cryptocurrency|Cryptocurrency|");
    debit_tcodes.put("T0022", "PayPal Seller Profiles|PayPal Seller Profiles|");
    debit_tcodes.put("T9701", "Funds Payable|Funds receivable|Funds provided by PayPal that need to be paid back.");
    debit_tcodes.put("T9702", "Funds Receivable|Funds receivable|Funds provided by PayPal that are being paid back.");
    debit_tcodes.put("T9700", "Payables and Receivables|Payables and Receivables|");
    debit_tcodes.put("T2103", "Reserve Hold|Reserve Hold|PayPal is holding x% of funds for y days as a condition for processing for you. This amount is part of your total balance and will not be available for withdrawal.");
    debit_tcodes.put("T2104", "Reserve Release|Reserve Hold|A reserve, when released, is now available for withdrawal.");
    debit_tcodes.put("T0202", "Conversion to Cover Negative Balance|Currency Conversion|PayPal-system generated.");
    debit_tcodes.put("T0200", "General Currency Conversion|Currency Conversion|Withdrawal of funds from one currency balance that is covered by funds from a different currency balance.");
    debit_tcodes.put("T0201", "User Initiated Currency Conversion|Currency Conversion|");
    debit_tcodes.put("T2000", "General intraaccount transfer|Account Transfer|");
    debit_tcodes.put("T2003", "Transfer To External GL Entity|Account Transfer|");
    debit_tcodes.put("T2004", "Receivables financing|Account Transfer|Applicable only in Brazil.");
    debit_tcodes.put("T1200", "General Account Adjustment|Adjustments|");
    debit_tcodes.put("T1204", "Incentive Adjustment|Adjustments|");
    debit_tcodes.put("T0803", "Balance Manager Account Bonus|Balance Manager Account Bonus Reversal|");
    debit_tcodes.put("T1000", "BillPay transaction|BillPay transaction|");
    debit_tcodes.put("T1601", "BML Credit - Transfer from BML|BML Credit - Transfer from BML|");
    debit_tcodes.put("T1801", "BML Withdrawal - Transfer to BML|BML WithdrawalTransfer to BML|");
    debit_tcodes.put("T1602", "Buyer Credit Payment|BML WithdrawalTransfer to BML|");
    debit_tcodes.put("T0806", "Bonus for First ACH Use|Bonus for First Bank Activity Reversal|");
    debit_tcodes.put("T0800", "General Bonus|Bonus Reversal|");
    debit_tcodes.put("T0807", "CC Security Charge Refund|CC Security Charge Refund|");
    debit_tcodes.put("T1203", "Charge-off Adjustment|Charge-off Adjustment|");
    debit_tcodes.put("T1900", "General Account Correction|Correction Adjustment|");
    debit_tcodes.put("T0903", "Coupon Redemption|Coupon applied|");
    debit_tcodes.put("T0808", "Credit Card Cash Back Bonus|Credit Card Cash Back Bonus|The monthly cash back accrued based on PayPal Extras Card signatures transactions for cash back program enrollees.");
    debit_tcodes.put("T0701", "Credit Card Deposit for Negative PayPal Account Balance|Credit Card Deposit|");
    debit_tcodes.put("T0505", "PayPal Debit Authorization|Debit Card Authorization|");
    debit_tcodes.put("T0801", "Debit Card Cash Back Bonus|Debit Card Bonus Reversal|Requires a PayPal debit card associated with the PayPal account. The monthly cash back accrued based on Merchant Debit Card signatures transactions for cash back program enrollees.");
    debit_tcodes.put("T0500", "General PayPal Debit Card Transaction|Debit card purchase|Requires a PayPal debit card associated with the PayPal account. The monthly cash back accrued based on Merchant Debit Card signatures transactions for cash back program enrollees.");
    debit_tcodes.put("T0501", "Virtual PayPal Debit Card Transaction|Debit card purchase|");
    debit_tcodes.put("T0303", "Electronic Funds Transfer Funding|Electronic Funds Transfer|");
    debit_tcodes.put("T0700", "General Credit Card Deposit|General Credit Card Deposit|Purchase with a credit card.");
    debit_tcodes.put("T0600", "General Credit Card Withdrawal|General Credit Card Withdrawal|Reversal of purchase with a credit card. Seen only in PayPal account of the credit card owner.");
    debit_tcodes.put("T1400", "General Dividend|General Dividend|");
    debit_tcodes.put("T0900", "General Incentive/ Certificate Redemption|General Incentive/Certificate Redemption|");
    debit_tcodes.put("T1100", "General Reversal|General Reversal|");
    debit_tcodes.put("T1700", "General withdrawal to not bank entity|General Withdrawal to Non-Bank Institution|");
    debit_tcodes.put("T3000", "General GI/Open wallet Transaction|Generic instrument (PLCC)|");
    debit_tcodes.put("T0901", "Gift Certificate Redemption|Gift Certificate applied|");
    debit_tcodes.put("T1116", "Instant Payment Review (IPR)reversal|Instant Payment Review|");
    debit_tcodes.put("T0802", "Merchant Referral Account Bonus|Merchant Referral Account Bonus Reversal|Must have created a Merchant Referral Bonus link.");
    debit_tcodes.put("T0905", "MSB Redemption|MSB Redemption|");
    debit_tcodes.put("T0503", "Hidden Virtual PayPal Debit Card Transaction|Other debit card activity|");
    debit_tcodes.put("T0502", "PayPal Debit Card Withdrawal to ATM|Other debit card activity|");
    debit_tcodes.put("T1102", "Reversal of Debit Card Transaction|Other debit card activity|Reversal of a debit card payment. Requires a PayPal debit card.");
    debit_tcodes.put("T1115", "Mass Pay Refund|Payment Refund|");
    debit_tcodes.put("T1107", "Payment Refund|Payment Refund|");
    debit_tcodes.put("T1119", "Generic Instrument/Open wallet Reversals (Buyer side)|Payment Reversals|");
    debit_tcodes.put("T1114", "Mass Pay Reversal|Payment Reversals|");
    debit_tcodes.put("T0805", "PayPal Protection Bonus, Payout for PayPal Buyer Protection, Payout for Full Protection with PayPal Buyer Credit|PayPal Bonus Reversal|");
    debit_tcodes.put("T0804", "PayPal Buyer Warranty Bonus|PayPal Buyer Warranty Bonus Reversal|");
    debit_tcodes.put("T0504", "PayPal Debit Card Cash Advance|PayPal Debit Card Cash Advance|");
    debit_tcodes.put("T0902", "Points Incentive Redemption|Points Incentive applied|");
    debit_tcodes.put("T1104", "Reversal of ACH Deposit|Reversal of ACH Deposit|");
    debit_tcodes.put("T1101", "Reversal of ACH Withdrawal Transaction|Reversal of ACH Withdrawal Transaction|Reversal of a withdrawal from PayPal balance to a bank account.");
    debit_tcodes.put("T1103", "Reversal of Points Usage|Reversal of Points Usage|");
    debit_tcodes.put("T1118", "Generic Instrument/Open wallet Reversals (Seller side)|Reversals|");
    debit_tcodes.put("T0904", "Reward Voucher Redemption|Reward Voucher applied|");
    debit_tcodes.put("T2001", "Consolidation Transfer|Settlement consolidation|");
    debit_tcodes.put("T0302", "ACH funding for Funds Recovery from Account balance|Transfer Deposit|");
    debit_tcodes.put("T0300", "Bank Deposit to PP Account|Transfer Deposit|");
    debit_tcodes.put("T0301", "PayPal Balance Manager Funding of PayPal Account|Transfer Deposit|PayPal-system generated.");
    debit_tcodes.put("T0401", "Auto-sweep|Transfer Withdrawal|");
    debit_tcodes.put("T0400", "General Withdrawal - Bank Account|Transfer Withdrawal|Settlement Withdrawal.");
    debit_tcodes.put("T0402", "Withdrawal to Hyperwallet|Transfer Withdrawal|");
    debit_tcodes.put("T0403", "Withdrawals initiated by user manually. Not related to automated scheduled withdrawals|Transfer Withdrawal|");
    debit_tcodes.put("T1701", "World Link withdrawal|World Link Withdrawal|");
    debit_tcodes.put("T1502", "Account Hold for ACH deposit|Account Holds|");
    debit_tcodes.put("T2111", "External Hold|Account Holds|");
    debit_tcodes.put("T1500", "General Account Hold|Account Holds|");
    debit_tcodes.put("T2101", "General Hold|Account Holds|");
    debit_tcodes.put("T2102", "General Hold Release|Account Holds|");
    debit_tcodes.put("T1503", "Hold on Available Balance|Account Holds|");
    debit_tcodes.put("T2109", "Gift Certificate Purchase|Gift Card Purchase|When a gift certificate is purchased by your buyer, then that amount is placed on hold.");
    debit_tcodes.put("T2110", "Gift Certificate Redemption|Gift Certificate Redemption|A gift certificate, when redeemed, is available for withdrawal.");
    debit_tcodes.put("T1105", "Reversal of General Account Hold|Hold|");
    debit_tcodes.put("T1501", "Account Hold for Open Authorization|Open PayPal Authorizations|");
    debit_tcodes.put("T2107", "Payment Hold|Payment review hold|Payment holds are funds that belong to you that we set aside, such as security deposit. This amount is part of your total balance and will not be available for withdrawal.");
    debit_tcodes.put("T2105", "Payment Review Hold|Payment review hold|A payment review hold is used to protect you against unauthorized fraud loss and for seller protection. While a transaction is on payment review hold, we recommend that you do not ship the item. We are reviewing this transaction for up to 24 hours.");
    debit_tcodes.put("T2113", "Blocked Payments|Release on compliance hold|");
    debit_tcodes.put("T2108", "Payment Release|Release on payment review hold|A payment hold, when released, is now available for withdrawal.");
    debit_tcodes.put("T2106", "Payment Review Release|Release on payment review hold|A payment review hold, when released, is now available for withdrawal.");
    debit_tcodes.put("T2112", "External Release|Release on risk hold|");
    debit_tcodes.put("T2114", "Tax hold|Tax hold|When a merchant account does not have a TIN and TPV crosses $600, then the gross amount is placed on hold.");
    debit_tcodes.put("T2301", "Tax withholding to IRS|Tax hold|");
  }
  public static HashMap<String, String> getCreditTcodesMap() {
    return credit_tcodes;
  }
      
  public static HashMap<String, String> getDebitTcodesMap() {
    return debit_tcodes;
  }
}
